version: '3.8'
services:
  webapi:
    build:
      context: .
      dockerfile: src/DockerWebApi/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - webapi
    networks:
      - app_network

networks:
  app_network:
    driver: bridge